spring:
  application:
    name: profit-calculation-api
  datasource:
    url: jdbc:mysql://localhost:3306/profit-calculation
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use-jdbc-metadata-defaults: false